/* Automatically generated by wasm2c */
#ifndef CMG_C_H_GENERATED_
#define CMG_C_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_env;
extern u32* w2c_env_0x5F_table_base(struct w2c_env*);
extern u32* w2c_env_a(struct w2c_env*);
extern u32* w2c_env_b(struct w2c_env*);
extern u32* w2c_env_c(struct w2c_env*);
extern u32* w2c_env_d(struct w2c_env*);
extern wasm_rt_memory_t* w2c_env_memory(struct w2c_env*);
extern wasm_rt_funcref_table_t* w2c_env_table(struct w2c_env*);

typedef struct w2c_cmg {
  struct w2c_env* w2c_env_instance;
  /* import: 'env' '__table_base' */
  u32 *w2c_env_0x5F_table_base;
  /* import: 'env' 'a' */
  u32 *w2c_env_a;
  /* import: 'env' 'b' */
  u32 *w2c_env_b;
  /* import: 'env' 'c' */
  u32 *w2c_env_c;
  /* import: 'env' 'd' */
  u32 *w2c_env_d;
  /* import: 'env' 'memory' */
  wasm_rt_memory_t *w2c_env_memory;
  /* import: 'env' 'table' */
  wasm_rt_funcref_table_t *w2c_env_table;
  u32 w2c_g5;
  u32 w2c_g6;
  u32 w2c_g7;
  u32 w2c_g8;
  u32 w2c_g9;
} w2c_cmg;

void wasm2c_cmg_instantiate(w2c_cmg*, struct w2c_env*);
void wasm2c_cmg_free(w2c_cmg*);
wasm_rt_func_type_t wasm2c_cmg_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: 'env' '$' */
void w2c_env_0x24(struct w2c_env*, u32, u32, u32);

/* import: 'env' 'A' */
void w2c_env_A(struct w2c_env*);

/* import: 'env' 'B' */
u32 w2c_env_B(struct w2c_env*, u32, u32);

/* import: 'env' 'C' */
void w2c_env_C(struct w2c_env*, u32);

/* import: 'env' 'D' */
u32 w2c_env_D(struct w2c_env*, u32, u32);

/* import: 'env' 'E' */
u32 w2c_env_E(struct w2c_env*, u32);

/* import: 'env' 'F' */
void w2c_env_F(struct w2c_env*, u32);

/* import: 'env' 'G' */
f64 w2c_env_G(struct w2c_env*, u32, u32, u32);

/* import: 'env' 'H' */
void w2c_env_H(struct w2c_env*, u32);

/* import: 'env' 'I' */
u32 w2c_env_I(struct w2c_env*, u32, u32);

/* import: 'env' 'J' */
void w2c_env_J(struct w2c_env*, u32, u32);

/* import: 'env' 'K' */
void w2c_env_K(struct w2c_env*, u32, u32, u32);

/* import: 'env' 'L' */
void w2c_env_L(struct w2c_env*, u32, u32);

/* import: 'env' 'M' */
void w2c_env_M(struct w2c_env*, u32, u32, u32);

/* import: 'env' 'N' */
void w2c_env_N(struct w2c_env*, u32, u32, u32, u32, u32);

/* import: 'env' 'O' */
void w2c_env_O(struct w2c_env*, u32, u32, u32);

/* import: 'env' 'P' */
void w2c_env_P(struct w2c_env*, u32, u32);

/* import: 'env' 'Q' */
void w2c_env_Q(struct w2c_env*, u32, u32, u32, u32, u32);

/* import: 'env' 'R' */
u32 w2c_env_R(struct w2c_env*, u32, u32);

/* import: 'env' 'S' */
u32 w2c_env_S(struct w2c_env*, u32, u32);

/* import: 'env' 'T' */
u32 w2c_env_T(struct w2c_env*, u32, u32);

/* import: 'env' 'U' */
void w2c_env_U(struct w2c_env*, u32);

/* import: 'env' 'V' */
u32 w2c_env_V(struct w2c_env*);

/* import: 'env' 'W' */
u32 w2c_env_W(struct w2c_env*, u32);

/* import: 'env' 'X' */
void w2c_env_X(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'Y' */
void w2c_env_Y(struct w2c_env*, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'Z' */
void w2c_env_Z(struct w2c_env*, u32, u32, u32, u32, u32);

/* import: 'env' '_' */
void w2c_env_0x5F(struct w2c_env*, u32, u32, u32, u32);

/* import: 'env' 'aa' */
void w2c_env_aa(struct w2c_env*, u32);

/* import: 'env' 'e' */
u32 w2c_env_e(struct w2c_env*);

/* import: 'env' 'f' */
void w2c_env_f(struct w2c_env*, u32);

/* import: 'env' 'g' */
u32 w2c_env_g(struct w2c_env*, u32, u32);

/* import: 'env' 'h' */
void w2c_env_h(struct w2c_env*, u32, u32, u32, u32, u32);

/* import: 'env' 'i' */
f64 w2c_env_i(struct w2c_env*);

/* import: 'env' 'j' */
void w2c_env_j(struct w2c_env*);

/* import: 'env' 'k' */
void w2c_env_k(struct w2c_env*, u32, u32);

/* import: 'env' 'l' */
void w2c_env_l(struct w2c_env*, u32);

/* import: 'env' 'm' */
u32 w2c_env_m(struct w2c_env*, u32, u32, u32, u32, u32);

/* import: 'env' 'n' */
u32 w2c_env_n(struct w2c_env*, u32, u32, u32, u32);

/* import: 'env' 'o' */
u32 w2c_env_o(struct w2c_env*, u32);

/* import: 'env' 'p' */
u32 w2c_env_p(struct w2c_env*, u32, u32, u32);

/* import: 'env' 'q' */
void w2c_env_q(struct w2c_env*);

/* import: 'env' 'r' */
void w2c_env_r(struct w2c_env*, u32);

/* import: 'env' 's' */
u32 w2c_env_s(struct w2c_env*, u32);

/* import: 'env' 't' */
u32 w2c_env_t(struct w2c_env*, u32, u32, u32);

/* import: 'env' 'u' */
void w2c_env_u(struct w2c_env*, u32, u32);

/* import: 'env' 'v' */
u32 w2c_env_v(struct w2c_env*);

/* import: 'env' 'w' */
u32 w2c_env_w(struct w2c_env*);

/* import: 'env' 'x' */
u32 w2c_env_x(struct w2c_env*, u32, u32, u32);

/* import: 'env' 'y' */
u32 w2c_env_y(struct w2c_env*, u32, u32, f64, u32, u32, u32, u32);

/* import: 'env' 'z' */
u32 w2c_env_z(struct w2c_env*, u32, u32);

extern const u64 wasm2c_cmg_min_env_memory;
extern const u64 wasm2c_cmg_max_env_memory;
extern const u8 wasm2c_cmg_is64_env_memory;
extern const u32 wasm2c_cmg_pagesize_env_memory;
extern const u32 wasm2c_cmg_min_env_table;
extern const u32 wasm2c_cmg_max_env_table;

/* export: 'ba' */
u32 w2c_cmg_ba(w2c_cmg*, u32);

/* export: 'ca' */
u32 w2c_cmg_ca(w2c_cmg*, u32);

/* export: 'da' */
u32 w2c_cmg_da(w2c_cmg*, u32);

/* export: 'ea' */
u32 w2c_cmg_ea(w2c_cmg*, u32, u32, u32, u32);

/* export: 'fa' */
u32 w2c_cmg_fa(w2c_cmg*, u32, u32, u32, u32);

/* export: 'ga' */
u32 w2c_cmg_ga(w2c_cmg*, u32, u32, u32, u32);

/* export: 'ha' */
u32 w2c_cmg_ha(w2c_cmg*, u32, u32, u32, u32);

/* export: 'ia' */
u32 w2c_cmg_ia(w2c_cmg*, u32, u32, u32, u32);

/* export: 'ja' */
u32 w2c_cmg_ja(w2c_cmg*, u32, u32, u32, u32);

/* export: 'ka' */
u32 w2c_cmg_ka(w2c_cmg*, u32, u32, u32, u32);

/* export: 'la' */
u32 w2c_cmg_la(w2c_cmg*, u32, u32, u32, u32);

/* export: 'ma' */
u32 w2c_cmg_ma(w2c_cmg*, u32, u32, u32, u32);

/* export: 'na' */
u32 w2c_cmg_na(w2c_cmg*, u32, u32, u32, u32);

/* export: 'oa' */
u32 w2c_cmg_oa(w2c_cmg*, u32, u32, u32, u32);

/* export: 'pa' */
u32 w2c_cmg_pa(w2c_cmg*, u32, u32, u32, u32);

/* export: 'qa' */
u32 w2c_cmg_qa(w2c_cmg*, u32, u32, u32, u32);

/* export: 'ra' */
u32 w2c_cmg_ra(w2c_cmg*, u32, u32, u32, u32);

/* export: 'sa' */
u32 w2c_cmg_sa(w2c_cmg*, u32, u32, u32, u32);

/* export: 'ta' */
u32 w2c_cmg_ta(w2c_cmg*, u32, u32, u32, u32);

/* export: 'ua' */
u32 w2c_cmg_ua(w2c_cmg*, u32, u32, u32, u32);

/* export: 'va' */
u32 w2c_cmg_va(w2c_cmg*, u32, u32, u32, u32);

/* export: 'wa' */
u32 w2c_cmg_wa(w2c_cmg*);

/* export: 'xa' */
void w2c_cmg_xa(w2c_cmg*);

/* export: 'ya' */
u32 w2c_cmg_ya(w2c_cmg*);

/* export: 'za' */
u32 w2c_cmg_za(w2c_cmg*, u32);

/* export: 'Aa' */
void w2c_cmg_Aa(w2c_cmg*, u32);

/* export: 'Ba' */
void w2c_cmg_Ba(w2c_cmg*, u32);

/* export: 'Ca' */
u32 w2c_cmg_Ca(w2c_cmg*, u32);

/* export: 'Da' */
u32 w2c_cmg_Da(w2c_cmg*, u32, u32);

/* export: 'Ea' */
u32 w2c_cmg_Ea(w2c_cmg*, u32);

/* export: 'Fa' */
u32 w2c_cmg_Fa(w2c_cmg*, u32);

/* export: 'Ga' */
void w2c_cmg_Ga(w2c_cmg*, u32);

/* export: 'Ha' */
void w2c_cmg_Ha(w2c_cmg*, u32, u32);

/* export: 'Ia' */
void w2c_cmg_Ia(w2c_cmg*, u32, u32, u32);

/* export: 'Ja' */
void w2c_cmg_Ja(w2c_cmg*, u32);

/* export: 'Ka' */
u32 w2c_cmg_Ka(w2c_cmg*);

/* export: 'La' */
void w2c_cmg_La(w2c_cmg*);

/* export: 'Ma' */
u32 w2c_cmg_Ma(w2c_cmg*, u32);

#ifdef __cplusplus
}
#endif

#endif  /* CMG_C_H_GENERATED_ */
